Setup: # General setup 
    n_events        :   250 # N Events/Batch
    n_batches       :   -1 # N batches training
    n_batches_val   :   -1 # N batches validation
    input_dir       :   "/vols/cms/lcr119/tuples/TauCP2802/ShuffleMerge/Training" 
    val_split       :   0.15 # proportion of files to be used for validation
    n_epochs        :   5
    epoch           :   0 # starting epoch

SetupNN: # Model setup
    model_name      :   "DNN" 
    dropout         :   0.0 # Fraction of Dropout regularisation
    use_weights     :   True # weighted inputs
    n_outputs       :   3 # Number of outputs

Inputs: # Inputs to be used (for DataLoader)
    truth           : 'true_category' # target variable
    feature_list    : ['pt_1', 'pt_2', 'eta_1', 'eta_2', 'phi_1', 'phi_2', 
                    'dR', 'm_vis', 'met', 'met_phi', 'n_jets'] 
    weights         : 'weight' # Set to None if not needed
    # TODO: Enable setting features in a separate config